import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import styles from './page.module.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Restaurant20',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={inter.className}>
      <header><Navbar /></header>
       <main className={styles.main}>
       {children}
       </main>
      
      </body>
    </html>
  )
}
